model_list:
- model_name: gemini-1.5-flash
  litellm_params:
    model: gemini/gemini-1.5-flash-latest
- model_name: gemini-1.5-pro
  litellm_params:
    model: gemini/gemini-1.5-pro-latest
- model_name: gemini-2.5-pro
  litellm_params:
    model: gemini/gemini-2.5-flash-preview-04-17
- model_name: gemini-2.0-flash
  litellm_params:
    model: gemini/gemini-2.0-flash
- model_name: deepseek-V3
  litellm_params:
    model: deepseek/deepseek-chat
    max_tokens: 1234567
- model_name: deepseek-R1
  litellm_params:
    model: deepseek/deepseek-reasoner
